### PR TITLE
Add authors field

### PR DESCRIPTION
**Pull request by maelle**
To make your names clickable like on https://docs.ropensci.org/riem/

### CODE REVIEW

**Comment by maelle** [comment]
Oops sorry for the mistake in your name!! :woman_facepalming:

**Comment by jonkeane** [comment]
No problem! I do it to myself with a domain like `jonkeane.com` but then preferring to write out Jonathan in text

**Comment by maelle** [comment]
Still, I'll pay more attention in the future.

**Comment by maelle** [comment]
(especially given my own domain name... no one calls me Ma :grin: )

**Comment by jonkeane** [comment]
Thanks, again, for the PR!

**Pull request merged**
